version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - network

volumes:
  mongo-data:

networks:
  network:
    driver: bridge